services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - N8N_CORS_ALLOWED_ORIGINS=http://localhost:3000
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    volumes:
      - ~/.n8n:/home/node/.n8n